default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: hr-func
  password: spider

development:
  <<: *default
  database: hr-func_development

test:
  <<: *default
  database: hr-func_test